trigger:
- master

stages:
- stage: BuildTest
  displayName: BuildTestDName
  jobs:
  - job: BuildJob
    pool:
      name: 'myagentpool'
    steps:
    - bash: |         
        chmod 777 test.sh
    - bash: |
        ./test.sh    
    - bash: |
        pwsh -Command ".\test.ps1"    
    - task: AzureCLI@2
      displayName: 'Testing Connection with Azure'
      inputs:
        azureSubscription: 'MyServiceConn'    
        scriptType: bash
        scriptLocation: inlineScript
        inlinescript: |
          az --version
          az group show -n 'TestAppDeployment'